#include <Preferences.h>

#include <WiFi.h>
#include <WebServer.h>
#include <DNSServer.h>
#include "WebPortal.h"
#include "config.h"

Preferences preferences;
const char *PREFERENCES_NAMESPACE = "patro_config";
const char *MACRO_KEY = "macro_seq";

DNSServer dnsServer;
WebServer server(80);
std::vector<MacroStep> currentSequence = {{1, 200}, {2, 200}};

// Função para salvar a sequência
void save_sequence_to_flash(const std::vector<MacroStep> &seq)
{
    String seqString = "";
    for (const auto &step : seq)
    {
        seqString += String(step.button) + "," + String(step.duration) + ";";
    }
    preferences.begin(PREFERENCES_NAMESPACE, false);
    preferences.putString(MACRO_KEY, seqString);
    preferences.end();
}

// Função para carregar a sequência
void load_sequence_from_flash()
{
    currentSequence.clear();
    preferences.begin(PREFERENCES_NAMESPACE, true);
    String seqString = preferences.getString(MACRO_KEY, "1,200;2,200;");
    preferences.end();

    int last_idx = 0;
    for (int i = 0; i < seqString.length(); i++)
    {
        if (seqString.charAt(i) == ';')
        {
            String stepStr = seqString.substring(last_idx, i);
            int commaIdx = stepStr.indexOf(',');
            if (commaIdx != -1)
            {
                int button = stepStr.substring(0, commaIdx).toInt();
                int duration = stepStr.substring(commaIdx + 1).toInt();
                currentSequence.push_back({button, duration});
            }
            last_idx = i + 1;
        }
    }
}

const char index_html[] PROGMEM = R"rawliteral(
<!DOCTYPE HTML>
<html>
<head>
    <title>PatroSmart Controller</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        :root { --bg-color: #2c2f33; --primary-color: #7289da; --text-color: #ffffff; --card-bg: #36393f; --border-color: #40444b; }
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background-color: var(--bg-color); color: var(--text-color); margin: 0; padding: 20px; display: flex; flex-direction: column; align-items: center; }
        .container { max-width: 600px; width: 100%; }
        h1, h2 { color: var(--primary-color); text-align: center; }
        .card { background-color: var(--card-bg); border-radius: 8px; padding: 20px; margin-bottom: 20px; border: 1px solid var(--border-color); }
        .controls { display: grid; grid-template-columns: repeat(auto-fit, minmax(100px, 1fr)); gap: 10px; margin-bottom: 20px; }
        .btn { background-color: var(--primary-color); color: white; border: none; padding: 12px; border-radius: 5px; font-size: 16px; cursor: pointer; transition: background-color 0.2s; }
        .btn:hover { background-color: #677bc4; }
        .btn:disabled { background-color: #555; cursor: not-allowed; }
        .duration-control { display: flex; flex-direction: column; gap: 10px; margin-top: 20px; }
        .duration-control label { font-weight: bold; }
        .slider-container { display: flex; align-items: center; gap: 15px; }
        input[type=range] { flex-grow: 1; accent-color: var(--primary-color); }
        input[type=number] { width: 80px; padding: 8px; border-radius: 5px; border: 1px solid var(--border-color); background-color: var(--bg-color); color: var(--text-color); font-size: 16px; }
        #sequence-list { list-style: none; padding: 0; }
        .sequence-item { display: flex; justify-content: space-between; align-items: center; background-color: var(--border-color); padding: 10px; border-radius: 5px; margin-bottom: 8px; }
        .sequence-item span { font-size: 1.1em; }
        .remove-btn { background-color: #f04747; color: white; border: none; border-radius: 5px; padding: 5px 10px; cursor: pointer; }
        .main-form button { width: 100%; padding: 15px; font-size: 18px; font-weight: bold; }
    </style>
</head>
<body>
    <div class="container">
        <h1>PatroSmart Controller</h1>

        <div class="card">
            <h2>1. Create Step</h2>
            <div class="controls" id="button-selector">
                <!-- Buttons are generated by JS -->
            </div>
            <div class="duration-control">
                <label for="duration">Step Duration (ms):</label>
                <div class="slider-container">
                    <input type="range" id="duration-slider" min="50" max="2000" value="200" step="10">
                    <input type="number" id="duration-input" min="50" max="5000" value="200">
                </div>
            </div>
            <button class="btn" id="add-step-btn" style="width:100%; margin-top: 20px;">Add Step to Macro</button>
        </div>

        <div class="card">
            <h2>2. Current Macro</h2>
            <div id="sequence-list"></div>
            <p id="empty-macro-msg">The macro is empty. Add steps above.</p>
        </div>
        
        <form id="save-form" class="main-form">
            <button class="btn" type="submit">Save Macro & Restart</button>
        </form>
    </div>

    <script>
        // --- GLOBAL STATE ---
        let macroSequence = [];
        let selectedButton = 1;

        // --- DOM ELEMENT REFERENCES ---
        const buttonSelector = document.getElementById('button-selector');
        const durationSlider = document.getElementById('duration-slider');
        const durationInput = document.getElementById('duration-input');
        const addStepBtn = document.getElementById('add-step-btn');
        const sequenceList = document.getElementById('sequence-list');
        const emptyMacroMsg = document.getElementById('empty-macro-msg');
        const saveForm = document.getElementById('save-form');

        // --- EVENT LISTENERS & INITIALIZATION ---

        // Sync duration slider and number input
        durationSlider.addEventListener('input', (e) => durationInput.value = e.target.value);
        durationInput.addEventListener('input', (e) => durationSlider.value = e.target.value);

        // Generate button selectors
        for (let i = 1; i <= 8; i++) {
            const btn = document.createElement('button');
            btn.className = 'btn';
            btn.textContent = `Button ${i}`;
            btn.dataset.buttonId = i;
            if (i === 1) btn.style.backgroundColor = '#4CAF50'; // Highlight the default selected button
            btn.addEventListener('click', () => {
                selectedButton = i;
                document.querySelectorAll('#button-selector .btn').forEach(b => b.style.backgroundColor = 'var(--primary-color)');
                btn.style.backgroundColor = '#4CAF50';
            });
            buttonSelector.appendChild(btn);
        }

        // Add step button listener
        addStepBtn.addEventListener('click', () => {
            const duration = parseInt(durationInput.value, 10);
            if (duration < 50) {
                alert("Duration must be at least 50ms.");
                return;
            }
            macroSequence.push({ button: selectedButton, duration: duration });
            renderSequence();
        });

        // Remove step from macro (using event delegation for performance)
        sequenceList.addEventListener('click', (e) => {
            if (e.target.classList.contains('remove-btn')) {
                const index = parseInt(e.target.dataset.index, 10);
                macroSequence.splice(index, 1);
                renderSequence();
            }
        });
        
        // Handle form submission using AJAX (fetch)
        saveForm.addEventListener('submit', (e) => {
            e.preventDefault(); // Prevent the default form submission which causes a page reload

            // Prepare the data string for the ESP32
            const formattedString = macroSequence.map(step => `${step.button},${step.duration}`).join(';');
            const payload = formattedString.length > 0 ? formattedString + ';' : '';
            
            // Provide user feedback
            const btn = saveForm.querySelector('button');
            const originalText = btn.textContent;
            btn.textContent = "Saving...";
            btn.disabled = true;

            const formData = new FormData();
            formData.append("seq", payload);

            // Send the data to the server
            fetch('/save', {
                method: 'POST',
                body: formData
            })
            .then(response => {
                if (response.ok) {
                    // On success, replace the page content with a success message
                    document.querySelector('.container').innerHTML = `
                        <h1>PatroSmart Controller</h1>
                        <div class="card" style="text-align: center;">
                            <h2 style="color: #4CAF50;">Success!</h2>
                            <p style="font-size: 1.2em;">Configuration saved.</p>
                            <p>The device is restarting and will enter Bluetooth mode.</p>
                            <p style="color: #aaa; font-size: 0.9em;">You can now close this page.</p>
                        </div>
                    `;
                } else {
                    alert("Error: Could not save macro.");
                    btn.textContent = originalText;
                    btn.disabled = false;
                }
            })
            .catch(error => {
                // A network error is expected here because the ESP32 restarts immediately after
                // sending the response, which can terminate the connection abruptly.
                // We can often assume success if an error occurs after a short period.
                console.error('Fetch error (likely due to device restart):', error);
                 // We still show the success message because the data was likely received.
                 document.querySelector('.container').innerHTML = `
                        <h1>PatroSmart Controller</h1>
                        <div class="card" style="text-align: center;">
                            <h2 style="color: #4CAF50;">Success!</h2>
                            <p style="font-size: 1.2em;">Configuration sent.</p>
                            <p>The device is restarting and will enter Bluetooth mode.</p>
                            <p style="color: #aaa; font-size: 0.9em;">You can now close this page.</p>
                        </div>
                    `;
            });
        });


        // --- UI RENDERING ---
        function renderSequence() {
            sequenceList.innerHTML = '';
            emptyMacroMsg.style.display = macroSequence.length === 0 ? 'block' : 'none';

            macroSequence.forEach((step, index) => {
                const item = document.createElement('div');
                item.className = 'sequence-item';
                item.innerHTML = `
                    <span>Press <b>Button ${step.button}</b> for <b>${step.duration}ms</b></span>
                    <button class="remove-btn" data-index="${index}">X</button>
                `;
                sequenceList.appendChild(item);
            });
        }

        // --- INITIAL DATA LOAD ---
        // Fetch the currently saved macro when the page loads
        document.addEventListener('DOMContentLoaded', () => {
            fetch('/get_macro')
                .then(response => response.text())
                .then(data => {
                    if (data && data.length > 0) {
                        const steps = data.split(';').filter(step => step); // filter removes empty strings
                        macroSequence = steps.map(step => {
                            const parts = step.split(',');
                            return { button: parseInt(parts[0], 10), duration: parseInt(parts[1], 10) };
                        });
                        renderSequence(); // Update the UI with the loaded macro
                    }
                })
                .catch(error => console.error('Error loading initial macro:', error));
        });
    </script>
</body>
</html>
)rawliteral";

void web_init()
{
    // A carga agora é feita no setup() principal, mas deixamos a função aqui.
    WiFi.mode(WIFI_AP);
    WiFi.softAP(AP_SSID, AP_PASS);
    dnsServer.start(53, "*", WiFi.softAPIP());

    server.on("/", []()
              { server.send(200, "text/html", index_html); });

    server.on("/get_macro", []()
              {
        String seqString = "";
        for (const auto& step : currentSequence) {
            seqString += String(step.button) + "," + String(step.duration) + ";";
        }
        server.send(200, "text/plain", seqString); });

    server.onNotFound([]()
                      { server.send(200, "text/html", index_html); });

    server.on("/save", []()
              {
        if (server.hasArg("seq")) {
            // Apenas para validação e armazenamento temporário
            std::vector<MacroStep> newSequence;
            String seqString = server.arg("seq");
            int last_idx = 0;
            for (int i = 0; i < seqString.length(); i++) {
                if (seqString.charAt(i) == ';') {
                    String stepStr = seqString.substring(last_idx, i);
                    int comma_idx = stepStr.indexOf(',');
                    if (comma_idx != -1) {
                        int button = stepStr.substring(0, comma_idx).toInt();
                        int duration = stepStr.substring(comma_idx + 1).toInt();
                        newSequence.push_back({button, duration});
                    }
                    last_idx = i + 1;
                }
            }
            // Se a nova sequência for válida, salva na flash
            if (!newSequence.empty()) {
                currentSequence = newSequence;
                save_sequence_to_flash(currentSequence);
            }
        }
        // 1. Envia apenas um código 200 OK (texto simples)
        server.send(200, "text/plain", "OK");
        
        // 2. Pequeno delay para garantir que o navegador receba a resposta antes do ESP morrer
        delay(100); 
        
        // 3. Reinicia
        ESP.restart(); });
    server.begin();
}

void web_stop()
{
    server.stop();
    dnsServer.stop();
    WiFi.mode(WIFI_OFF);
}
void web_loop()
{
    dnsServer.processNextRequest();
    server.handleClient();
}
std::vector<MacroStep> web_get_sequence() { return currentSequence; }

void web_load_default_sequence()
{
    load_sequence_from_flash();
}